# Generated by Django 5.0.2 on 2025-03-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='competitors',
            field=models.ManyToManyField(related_name='competitor_analyses', to='competitors.competitor'),
        ),
    ]
